"""Esquema inicial (versión 1 en producción)

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 11:41:28.331246
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('permisos', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sociedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['sociedades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('debe_cambiar_password', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('propietaria_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('modalidad', sa.String(length=40), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('cp', sa.String(length=10), nullable=True),
    sa.Column('ref_catastral', sa.String(length=30), nullable=True),
    sa.Column('num_registro_turistico', sa.String(length=60), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['sociedades.id'], ),
    sa.ForeignKeyConstraint(['propietaria_id'], ['sociedades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activos_company_id'), ['company_id'], unique=False)

    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('entidad', sa.String(length=40), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_fecha'), ['fecha'], unique=False)

    op.create_table('terceros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=160), nullable=True),
    sa.Column('documento_tipo', sa.String(length=10), nullable=True),
    sa.Column('documento_num', sa.String(length=30), nullable=True),
    sa.Column('nacionalidad', sa.String(length=60), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('iban', sa.String(length=40), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['sociedades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terceros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terceros_company_id'), ['company_id'], unique=False)

    op.create_table('asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['activos.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['sociedades.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asignaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asignaciones_user_id'), ['user_id'], unique=False)

    op.create_table('planes_preventivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('normativa', sa.String(length=200), nullable=True),
    sa.Column('periodicidad_dias', sa.Integer(), nullable=False),
    sa.Column('proxima_fecha', sa.Date(), nullable=False),
    sa.Column('proveedor', sa.String(length=160), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['activos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planes_preventivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planes_preventivos_asset_id'), ['asset_id'], unique=False)

    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('bloque', sa.String(length=40), nullable=True),
    sa.Column('uso', sa.String(length=20), nullable=False),
    sa.Column('tipologia', sa.String(length=60), nullable=True),
    sa.Column('planta', sa.String(length=10), nullable=True),
    sa.Column('superficie_m2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dormitorios', sa.Integer(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('ref_catastral', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('renta_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tarifa_base_noche', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coef_participacion', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('cuota_comunidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('anejos', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['activos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'codigo')
    )
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unidades_asset_id'), ['asset_id'], unique=False)

    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=40), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('renta_mensual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fianza', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('garantia_adicional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dia_pago', sa.Integer(), nullable=False),
    sa.Column('indice_actualizacion', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['terceros.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratos_unit_id'), ['unit_id'], unique=False)

    op.create_table('ordenes_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('asignado_a', sa.String(length=120), nullable=True),
    sa.Column('proveedor', sa.String(length=160), nullable=True),
    sa.Column('coste_estimado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coste_real', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bloquea_unidad', sa.Boolean(), nullable=False),
    sa.Column('fecha_apertura', sa.Date(), nullable=False),
    sa.Column('fecha_prevista', sa.Date(), nullable=True),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('solucion', sa.Text(), nullable=True),
    sa.Column('abierta_por', sa.Integer(), nullable=True),
    sa.Column('conf_mto_por', sa.Integer(), nullable=True),
    sa.Column('conf_mto_fecha', sa.DateTime(), nullable=True),
    sa.Column('conf_limpieza_por', sa.Integer(), nullable=True),
    sa.Column('conf_limpieza_fecha', sa.DateTime(), nullable=True),
    sa.Column('cerrada_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abierta_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['activos.id'], ),
    sa.ForeignKeyConstraint(['cerrada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['conf_limpieza_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['conf_mto_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_preventivos.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordenes_trabajo_asset_id'), ['asset_id'], unique=False)

    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('localizador', sa.String(length=60), nullable=True),
    sa.Column('canal', sa.String(length=30), nullable=False),
    sa.Column('fecha_entrada', sa.Date(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=False),
    sa.Column('adultos', sa.Integer(), nullable=False),
    sa.Column('ninos', sa.Integer(), nullable=False),
    sa.Column('importe_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('importe_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['terceros.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservas_fecha_entrada'), ['fecha_entrada'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_fecha_salida'), ['fecha_salida'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_unit_id'), ['unit_id'], unique=False)

    op.create_table('recibos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('concepto', sa.String(length=60), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('importe_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lease_id', 'periodo', 'concepto')
    )
    with op.batch_alter_table('recibos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recibos_lease_id'), ['lease_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recibos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recibos_lease_id'))

    op.drop_table('recibos')
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservas_unit_id'))
        batch_op.drop_index(batch_op.f('ix_reservas_fecha_salida'))
        batch_op.drop_index(batch_op.f('ix_reservas_fecha_entrada'))

    op.drop_table('reservas')
    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordenes_trabajo_asset_id'))

    op.drop_table('ordenes_trabajo')
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_unit_id'))

    op.drop_table('contratos')
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unidades_asset_id'))

    op.drop_table('unidades')
    with op.batch_alter_table('planes_preventivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planes_preventivos_asset_id'))

    op.drop_table('planes_preventivos')
    with op.batch_alter_table('asignaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asignaciones_user_id'))

    op.drop_table('asignaciones')
    with op.batch_alter_table('terceros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terceros_company_id'))

    op.drop_table('terceros')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_fecha'))

    op.drop_table('auditoria')
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activos_company_id'))

    op.drop_table('activos')
    op.drop_table('usuarios')
    op.drop_table('sociedades')
    op.drop_table('roles')
    # ### end Alembic commands ###
