"""Contratos de alojamiento

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 11:53:44.150127
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos_alojamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('plantilla', sa.String(length=80), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contratos_alojamiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratos_alojamiento_reservation_id'), ['reservation_id'], unique=False)

    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato_representante', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('contrato_representante_dni', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contrato_email', sa.String(length=160), nullable=True))

    with op.batch_alter_table('terceros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('municipio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pais', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terceros', schema=None) as batch_op:
        batch_op.drop_column('pais')
        batch_op.drop_column('municipio')
        batch_op.drop_column('cp')

    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.drop_column('contrato_email')
        batch_op.drop_column('contrato_representante_dni')
        batch_op.drop_column('contrato_representante')

    with op.batch_alter_table('contratos_alojamiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_alojamiento_reservation_id'))

    op.drop_table('contratos_alojamiento')
    # ### end Alembic commands ###
