"""Documentos de identidad escaneados

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 13:36:51.746504
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_terceros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('cara', sa.String(length=10), nullable=False),
    sa.Column('fichero', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=60), nullable=False),
    sa.Column('tamano', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('lectura', sa.JSON(), nullable=True),
    sa.Column('subido', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['terceros.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos_terceros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_terceros_contact_id'), ['contact_id'], unique=False)

    with op.batch_alter_table('terceros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('num_soporte', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fecha_caducidad_doc', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terceros', schema=None) as batch_op:
        batch_op.drop_column('fecha_caducidad_doc')
        batch_op.drop_column('num_soporte')
        batch_op.drop_column('sexo')

    with op.batch_alter_table('documentos_terceros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_terceros_contact_id'))

    op.drop_table('documentos_terceros')
    # ### end Alembic commands ###
