"""Documentos escaneados antes del alta del cliente

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-02 14:02:46.152273
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_terceros', schema=None) as batch_op:
        batch_op.alter_column('contact_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_terceros', schema=None) as batch_op:
        batch_op.alter_column('contact_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
