"""Facturación: facturas con serie correlativa por activo, domicilio fiscal de las sociedades e IVA

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-02 14:48:05.359701
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=12), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('rectifica_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('emisor', sa.JSON(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('cliente', sa.JSON(), nullable=False),
    sa.Column('fecha_expedicion', sa.Date(), nullable=False),
    sa.Column('fecha_operacion', sa.Date(), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('base_imponible', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cuota_iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exencion', sa.String(length=200), nullable=True),
    sa.Column('forma_pago', sa.String(length=30), nullable=True),
    sa.Column('charge_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('huella', sa.String(length=64), nullable=False),
    sa.Column('huella_anterior', sa.String(length=64), nullable=True),
    sa.Column('creada', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['activos.id'], ),
    sa.ForeignKeyConstraint(['charge_id'], ['recibos.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['sociedades.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['terceros.id'], ),
    sa.ForeignKeyConstraint(['rectifica_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('serie', 'anio', 'numero')
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_fecha_expedicion'), ['fecha_expedicion'], unique=False)

    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serie_factura', sa.String(length=10), nullable=True))

    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_iva', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('recibos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_iva', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('sociedades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('cp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('municipio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###
    _datos()


# Series de los activos de partida y permisos nuevos en los roles existentes (en una base nueva no hay
# filas: lo hace la carga inicial)
SERIES = {"BAB35": "B35", "SFL": "SF", "SAE": "SA"}
PERMISOS_NUEVOS = {
    "Dirección Grupo": ["facturas.ver", "facturas.rectificar"],
    "Dirección Sociedad": ["facturas.ver", "facturas.rectificar"],
    "Administración / Finanzas": ["facturas.ver", "facturas.rectificar"],
    "Gestor Alquiler Residencial": ["facturas.ver"],
    "Recepción": ["facturas.ver"],
}


def _datos() -> None:
    conn = op.get_bind()
    activos = sa.table("activos", sa.column("codigo", sa.String), sa.column("serie_factura", sa.String))
    for codigo, serie in SERIES.items():
        conn.execute(activos.update().where(activos.c.codigo == codigo, activos.c.serie_factura.is_(None))
                     .values(serie_factura=serie))
    roles = sa.table("roles", sa.column("id", sa.Integer), sa.column("nombre", sa.String),
                     sa.column("permisos", sa.JSON))
    for rid, nombre, permisos in conn.execute(sa.select(roles.c.id, roles.c.nombre, roles.c.permisos)).all():
        nuevos = [p for p in PERMISOS_NUEVOS.get(nombre, []) if p not in (permisos or [])]
        if nuevos:
            conn.execute(roles.update().where(roles.c.id == rid).values(permisos=list(permisos or []) + nuevos))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sociedades', schema=None) as batch_op:
        batch_op.drop_column('provincia')
        batch_op.drop_column('municipio')
        batch_op.drop_column('cp')
        batch_op.drop_column('direccion')

    with op.batch_alter_table('recibos', schema=None) as batch_op:
        batch_op.drop_column('tipo_iva')

    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_column('tipo_iva')

    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.drop_column('serie_factura')

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_fecha_expedicion'))
        batch_op.drop_index(batch_op.f('ix_facturas_company_id'))
        batch_op.drop_index(batch_op.f('ix_facturas_asset_id'))

    op.drop_table('facturas')
    # ### end Alembic commands ###
