"""Adjuntos de las órdenes de trabajo y avisos por correo

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 03:55:13.957072
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avisos_enviados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('destinatario', sa.String(length=160), nullable=True),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avisos_enviados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avisos_enviados_clave'), ['clave'], unique=False)
        batch_op.create_index(batch_op.f('ix_avisos_enviados_fecha'), ['fecha'], unique=False)

    op.create_table('adjuntos_ot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('fichero', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=60), nullable=False),
    sa.Column('tamano', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('subido', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['ordenes_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adjuntos_ot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adjuntos_ot_work_order_id'), ['work_order_id'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avisos', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('avisos')

    with op.batch_alter_table('adjuntos_ot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adjuntos_ot_work_order_id'))

    op.drop_table('adjuntos_ot')
    with op.batch_alter_table('avisos_enviados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avisos_enviados_fecha'))
        batch_op.drop_index(batch_op.f('ix_avisos_enviados_clave'))

    op.drop_table('avisos_enviados')
    # ### end Alembic commands ###
