"""Plano interactivo: bloqueos de apartamentos, zona común en las OT y tipologías de Suite Aeropuerto

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-05 04:28:12.987564
"""
from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloqueos_unidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('hasta', sa.Date(), nullable=True),
    sa.Column('desde', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('levantado', sa.DateTime(), nullable=True),
    sa.Column('levantado_por', sa.Integer(), nullable=True),
    sa.Column('nota_levantado', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['levantado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bloqueos_unidad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bloqueos_unidad_unit_id'), ['unit_id'], unique=False)

    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zona', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_ordenes_trabajo_zona'), ['zona'], unique=False)

    # ### end Alembic commands ###
    _tipologias_sae()


# Tipologías de Suite Aeropuerto según la ficha de apartamentos (en una base nueva lo hace la carga inicial)
TERRAZA = {211, 212, 216, 217, 246, 247, 250, 251}
TERRAZA_GRANDE = {213, 214, 215, 248, 249}
GRANDE = {260, 316, 351, 364, 416, 451, 464, 516, 551, 564}


def _tipologias_sae() -> None:
    conn = op.get_bind()
    activos = sa.table("activos", sa.column("id", sa.Integer), sa.column("codigo", sa.String))
    unidades = sa.table("unidades", sa.column("id", sa.Integer), sa.column("asset_id", sa.Integer),
                        sa.column("codigo", sa.String), sa.column("tipologia", sa.String),
                        sa.column("dormitorios", sa.Integer))
    sae = conn.execute(sa.select(activos.c.id).where(activos.c.codigo == "SAE")).scalar()
    if sae is None:
        return
    base = "Apartamento 1 dormitorio"
    for uid, codigo, tipologia in conn.execute(sa.select(unidades.c.id, unidades.c.codigo, unidades.c.tipologia)
                                               .where(unidades.c.asset_id == sae)).all():
        try:
            n = int(codigo.split("-")[-1])
        except ValueError:
            continue
        valores = None
        if n == 127 and tipologia == base:  # la ficha la da como de 2 dormitorios
            valores = {"tipologia": "Apartamento 2 dormitorios", "dormitorios": 2}
        elif tipologia == base and n in TERRAZA:
            valores = {"tipologia": base + " con terraza"}
        elif tipologia == base and n in TERRAZA_GRANDE:
            valores = {"tipologia": base + " con terraza grande"}
        elif tipologia == base and n in GRANDE:
            valores = {"tipologia": base + " grande"}
        if valores:
            conn.execute(unidades.update().where(unidades.c.id == uid).values(**valores))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordenes_trabajo_zona'))
        batch_op.drop_column('zona')

    with op.batch_alter_table('bloqueos_unidad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bloqueos_unidad_unit_id'))

    op.drop_table('bloqueos_unidad')
    # ### end Alembic commands ###
