"""Facturas con varias líneas e IVA por línea, y catálogo de servicios (limpieza, aparcamiento...)

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-05 05:00:22.459472
"""
from alembic import op
import sqlalchemy as sa


revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['activos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lineas', sa.JSON(), nullable=True))
        batch_op.alter_column('tipo_iva',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)

    # ### end Alembic commands ###
    # Servicios iniciales para todos los activos, al 21 %; el precio se fija en Facturación → Servicios
    servicios = sa.table("servicios", sa.column("nombre", sa.String), sa.column("unidad", sa.String),
                         sa.column("tipo_iva", sa.Numeric), sa.column("activo", sa.Boolean))
    op.bulk_insert(servicios, [{"nombre": n, "unidad": u, "tipo_iva": 21, "activo": True} for n, u in (
        ("Limpieza extra", "ud"), ("Plaza de aparcamiento exterior", "día"), ("Plaza de garaje", "día"),
        ("Plaza de garaje", "mes"), ("Lavandería", "ud"))])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.alter_column('tipo_iva',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.drop_column('lineas')

    op.drop_table('servicios')
    # ### end Alembic commands ###
